# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/YahiaMohamed90/CWD-Argo-CD-files.git
      targetRevision: HEAD
      path: promethues
      ref: master
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: "19.7.2"
      helm:
        values: |
            server:
              service:
                type: ClustrtIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  autoSync:
    prune: true
    selfHeal: true
    interval: 1m  # Adjust the interval as needed (e.g., 5m for 5 minutes)   
